import numpy as np
import bisect
class LCSFinder:
    def __init__(self, s1, s2):
        ...
    def FindLCP(self, i, j):
        ...
    def GetS(self):
        ...
    def GetSA(self):
        ...
    def BuildSuffixArray(self):
        ...
    def ComputeAllLCSs(self, inds):
        ...
